# Main Configuration file.
# BlockDynastyEconomy Plugin
# Version: 1.1.5

# Developer(s): @Federkone.

#EN(English), ES(Spanish),RU(Russia),ZH(Chinese),DE(Deutschland),IT(Italian),FR(French),JA(Japan) You can also create your own language file in the language folder.
lang: EN

#The plugin is designed to work in both offline and online modes.
#Therefore:
#In online mode: the user will be validated with their UUID, and if a change in nickname is detected, it will be updated in the database.
#In offline mode: the user will be validated with their nickname, and if a change in UUID is detected, it will be updated in the database.
#As you can see, selecting this option from the beginning is critical and must be synchronized with your network, since
#changing the operating mode from offline to online during the process will result in the total loss of information.
#It is impossible to assume that the UUIDs uploaded in offline mode are true, as they may be random data not supported by Mojang.
#-> Make your decision carefully and set the same value on all your servers. Thank you.
online: true

#Hardcash
# this option enables or disables the Hard cash system. ItemStack/Items based economy.
# when enabled, players will have a physical item in their inventory that represents their money.
# when disabled, players will have a virtual balance that is not represented by any item.
#Disclaimer: this system its objected to vulnerabilities and exploits related to the game engine or another plugins: example item duplication's, be careful and Test.
HardCash:
  enable: false
  customHeadTexture: true

#Console log some information for debugging.
debug: false

#This parameter forces the Minecraft API to strictly use the vanilla color system.
#It's not necessary to change this option unless you're experiencing compatibility issues.
#Default is false.
forceVanillaColorsSystem: false

#Enable or Disable Vault integration.
vault: true
# Enable or Disable the transaction log vault integration. This will log all transactions operations to vault.
# Note: This option enabled cause a lot of logs because every transaction will be logged to vault integrations.
transaction_log_vault: false

# Enable or Disable the transaction log. The transaction log is a log of all transactions that
transaction_log: true

sql:
  # You have three valid storage methods, mariadb/mysql/sqlite/h2. You would have to enter the database credentials below.
  type: h2
  # you would have to enter the database credentials down below.
  database: minecraft
  host: localhost
  port: 3306
  username: root
  password: ''
  # EnableWebEditorSqlServer is to enable the web sql server for h2/sqlite database in http://localhost:8082,
  # if you want to use the web console of h2/sqlite database, you have to set this to true.
  # With this you can manage the h2/sqlite database from a web browser.
  EnableWebEditorSqlServer: false

# Redis configuration, this replaces module messaging with Proxy:Velocity, BungeeCord, for sync cache balances,notifications between servers.
redis:
  enabled: false
  host: localhost
  port: 6379
  password: ""
  user: default


# enableDistanceLimitOffer true, maxDistanceOffer is the maximum distance in blocks that a player
# can be to make/accept an offer/trade currencies. example: 5 blocks, 10 blocks, etc.
# expireCacheTopMinutes is the time in minutes that the cache of the top balances will expire.
# example: 5 minutes, 10 minutes, etc.
#WORK IN PROGRESS FEATURE
#enableDistanceLimitOffer: true
#maxDistanceOffer: 5.0
#expireCacheTopMinutes: 5  # this option is hardcoded in the code,WORK IN PROGRESS FEATURE